var GAME_LEVELS = [
   ["                                                                               ",
   "                                                                                ",
   "                                                                                ",
   "                                  yy                                            ",
   "                               yyyyyy                                           ",
   "                            yyyyyy                                              ",
   "      y                                         yy                       y      ",
   "    yyyyyyy                                      yy                   yyyyyy    ",
   "  yyyyy                                                              yyyyy      ",
   "                                                                           xxxx ",
   "  xxxxxx                      ooo                                             b ",
   "  b                     o  xxxxxx  o                      xxx                 b ",
   "  b                    o        bxxx      o         xxxx                      b ",
   "  b                  xxx                        oo         oo                 b ",
   "  b                xxbbb                 opo    x          xxxxx              b ",
   "  b            oxxxb!!!bxxx             xxxxx                             &   b ",
   "  b  @    oo   xbbbbbbbbbbbxx          obbbbbxx                      xxxxxxxxxbx",
   "xxbxxxxxxxxxx!!bbbbbbbbbbbbbbxxx!!!!xxxxbbbbbbbxx!!!!!xxxxxxxxxxxxxxx!!!!!!!!bbb",
   "bbbbbbbbbbbbb!!bbbbbbbbbbbbbbbb!!!!!!bbbbbbbbbbbb!!!!!bbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbb!!bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb!!!!!bbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb!!!!!bbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                 yyyy             ",
   "                                                                                               yyyy               ",
   "                                    yyyyyy                x!!!!!x                                                 ",
   "                                        yyyy              b!!!!!b                                                b",
   "                                                           b!!!b           x       x                             b",
   "                                                            b!b           xb!!!!!!!bx                            b",
   "         yyy                                                bvb           bbbbbvbbbbb                            b",
   "       yyyyyyy                                                                b b                  xx            b",
   "         yyyyyyy                                              o                               po                 b",
   "xx                                                    xx                                    xxxx        o    &   b",
   "b                                                                                                       x    x   b",
   "b                                              xxxx        oo          o              xxxx!!!!!!!!!!!!!!!!!!!!!!!b",
   "b                                                         xxx   x             oooo xxxbbbb!!!!!!!!!!!!!!!!!!!!!!!b",
   "b                                       o o                            p  xxxxxxxxxbbbbbbb!!!!!!!!!!!!!!!!!!!!!!!b",
   "b   @                  pooo            xxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxbbbbbbbbbbbbbbbb!!!!!!!!!!!!!!!!!!!!!!!b",
   "b   b                  xxxx   o        bbbbbbb!!!!!!!!!!!!!!!!!!!!!!bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bxxxbxxxxxxxxx                xx       bbbbbbb!!!!!!!!!!!!!!!!!!!!!!bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbb          o          p  xbbbbbbb!!!!!!!!!!!!!!!!!!!!!!bbbbbbbbbbbbbbbbbbbb!!!!!!!bbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbb                    xxxxbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb!!!!!!!!!bbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbxxxxxxx            obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbbbbbbbb          ooxbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbbbbbbbb         ooobbbbbbbbbbbbbbbbbbbbbbb!!!!!!!!!!bbbbbbbbbbbbbbbbbbb!!!!!!!!bbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbbbbbbbbxx!!!!xxxxxxbbbbbbbbbbbbbbbbbbbb!!!!!!!!!!!!!!!bbbbbbbbbbbbbbbbbbb!!!!!!!!!!bbbbbbbbbbbbbbbbb",
   "bbb!!!!!!!!!!!!!!!!bbbb!!!!bbbbbbbbbbbbbbbbbbbbbbbbb!!!!!!!!!!!!!!!!!bbbbbbbbbbbbbbbbbbbb!!!!!bbbbbbbbbbbbbbbbbbbb",
   "bbb!!!!!!!!!!!!!!!!bbbb!!!!bbbbbbbbbbbbbbbbbbbbbbbbbbb!!!!!!!!!!!!!!bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbb!!!!!!!!!!!!!!!!bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb!!!!!!!bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"],
  ["                                                                                                              ",
   "x                                                                                                             ",
   "b                                                                                                             ",
   "b                                                                                                             ",
   "b                                                                                                             ",
   "b                                yyy                                                                          ",
   "b  @  *                        yyyyyyyyy                                                                      ",
   "bxxxxxx                          yyyyyyyyy                                                                    ",
   "bbbbbbb                            yyyy                                                                       ",
   "bbbbbbb                                                                                                       ",
   "bbbbbbbo                                                    yyy                                               ",
   "bbbbbbbo        o                                        yyyyyyyy                                             ",
   "bbbbbbbo       xx                                      yyyyyyy                                                ",
   "bbbbbbbo      xb                                         yyy                                                  ",
   "bbbbbbb       bb                                                                                              ",
   "bbbbbbbx!!!!xxbb                                                                                              ",
   "bbbbbbbb!!!!bbbb                       xxxxxxxxxxxxxxxxxxxxx                                                  ",
   "bbbbbbbb!!!!bbbb                       b!!v!!!!!!!!!!!!!v!!bbbb                   yy                          ",
   "bbbbbbbbbvbbbbbb                  xxxxxb                   bbbb                  yyyyyy                       ",
   "bbbbb                             bbbbbb                   bbbb                     yyyyy                     ",
   "bbbbb                             bbbbbb     ooooooooo     bbbbb                                 xx           ",
   "bbbbboo                           bbbbbb     ooooooooo     bbbbb                   x            bbbx          ",
   "bbbbbooo                   x      bbbbbb     ooooooooo     bbbbb                  bbb        bbbbbbb          ",
   "bbbbbxxxxxxxxxxxx= =       b  =   bbbbbb                   bbbbb  xxxxxxxxxxxxxxxbbbbbxxxxxxbbbbbbbbxxxxxxxxxx",
   "bbbbbbbbbbbbbbbbbxxxxxxxxxxb      bbbbbb      xxxxxxx      bbbbbxxb                         |            bbbbb",
   "bbbbbbbbbbbbbbbbboooooooooo                                                                   |           bbbb",
   "bbbbbbbbbbbbbbbbbooooooooooo                    ooo                        o                              bbbb",
   "bbbbbbbbbbbbbbbbbxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   =       =   x  oooooo               bbbb",
   "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        bbbb",
   "                                                                                         bbbbbbbbb        bbbb",
   "                                                                                           bbbbbbb       xbbbb",
   "          yyyy                               o                                               bbbbb       =bbbb",
   "         yyyyyyyyy                           x                                                 bbbo       bbbb",
   "xxxxx       yyyyyyyy                        xbx        xxx                                       bx       bbbb",
   "bbb                                       xxbbbxxx        x                                      b       obbbb",
   "bbb                                      xbb!bbbbbxx                                        b    b      xxbbbb",
   "bbb                                      xbbbbb!!!!!v                                      bbb   b        bbbb",
   "bbb                         xo          obbbbbbbbbbb           xxxxxx                xxxxbbbbbxxxb        bbbb",
   "bbb                         bxo        oxbbbb                    |  bx               b       |            bbbb",
   "bbb                         bbo       oxbbbbbxxx               |    bbx              b                    bbbb",
   "bbb         oo               bxo     oxbbbbbb            xxx        bbbx             b      |             bbbb",
   "bbb        oooo               bxx   oxbbbbbbb           x          obbbbx            b                   obbbb",
   "bbb       oooooo               bbxxxxbbbbbbbb                      obbbbbx                |             oobbbb",
   "bbb  &  xxxxxxxxxx           oobbbbbbbbbbbbbbxx                    obbbbbbx      oooo                  ooobbbb",
   "bbbxxxxxbbbbbbbbbbxxxxxxxxxxxxb!!!!!!!!!!!!!!!bxxxxxxxxxxxxxxxxxxxxxbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbbbb",
   "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
   "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"],
  ["                                                                               ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",  
   "                  y       y               y        y                            ",
   "                   y     y                y        y                 y          ",
   "                    y   y                 y        y                 y          ",
   "                     y y                  y        y                 y          ",
   "                      y   yyy   y   y     y    y   y   yyy           y     xxxx ",
   "  xxxxxx             y   y   y  y   y     y    y   y  y   y yyyy     y        x ",
   "  b                 y    y   y  y   y     y    y   y  y   y y   y    y        x ",
   "  b                y     y   y  y   y      y   y  y   y   y y   y             x ",
   "  b               y       yyy    yyy        yyy yy     yyy  y   y    y        x ",
   "  b                                                                           x ",
   "  b                                                                           x ",
   "  b@oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooox ",
   "  bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
